accounts/urls.py
# accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('freelancer/dashboard/', views.freelancer_dashboard, name='freelancer_dashboard'),
    path('employer/dashboard/', views.employer_dashboard, name='employer_dashboard'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('employer/profile/', views.employer_profile_view, name='employer_profile'),
    path('employer/edit-profile/', views.edit_employer_profile, name='edit_employer_profile'),
    path('employer/post-job/', views.post_job, name='post_job'),
    path('employer/applicant/<int:application_id>/', views.applicant_profile, name='applicant_profile'),
    path('job/<int:job_id>/', views.job_detail, name='job_detail'),
    path('job/<int:job_id>/edit/', views.edit_job, name='edit_job'),
    path('job/<int:job_id>/delete/', views.delete_job, name='delete_job'),
    path('application/<int:application_id>/reject/', views.reject_application, name='reject_application'),
]

jobcamp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('website.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from website.views import *


app_name = 'website'

urlpatterns=[
    path('', home, name='home'),
    path('hello', hello, name='hello'),
    path('contact',contact, name="contact" ),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% block title %}جاب کمپ - قالب کاریابی آنلاین{% endblock %}</title>
  <link rel="shortcut icon" href="{% static 'image/favicon.png' %}" type="image/x-icon">
  <!-- Bootstrap, fonts & icons -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
  <link rel="stylesheet" href="{% static 'fonts/icon-font/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'fonts/typography-font/typo.css' %}">
  <link rel="stylesheet" href="{% static 'fonts/fontawesome-5/css/all.css' %}">
  <!-- Custom stylesheet -->
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
  <div class="site-wrapper overflow-hidden">
    <!-- Header Area -->
    <header class="site-header site-header--menu-right bg-default py-7 py-lg-0 site-header--absolute site-header--sticky">
      <div class="container">
        <nav class="navbar site-navbar offcanvas-active navbar-expand-lg px-0 py-0">
          <!-- Brand Logo -->
          <div class="brand-logo">
            <a href="{% url 'website:home' %}">
              <img src="{% static 'image/logo-main-black.png' %}" alt="لوگوی جاب کمپ" class="light-version-logo default-logo">
              <img src="{% static 'image/logo-main-white.png' %}" alt="لوگوی جاب کمپ" class="dark-version-logo">
            </a>
          </div>
          <div class="collapse navbar-collapse" id="mobile-menu">
            <div class="navbar-nav-wrapper">
              <ul class="navbar-nav main-menu">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'website:home' %}">خانه</a>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle gr-toggle-arrow" id="navbarDropdown2" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">صفحه‌ها<i class="icon icon-small-down"></i></a>
                  <ul class="gr-menu-dropdown dropdown-menu" aria-labelledby="navbarDropdown2">
                    <li class="drop-menu-item">
                      <a href="{% url 'accounts:employer_profile' %}">پروفایل شرکت</a>
                    </li>
                    <li class="drop-menu-item">
                      <a href="{% url 'website:contact' %}">تماس با ما</a>
                    </li>
                  </ul>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'website:contact' %}">پشتیبانی</a>
                </li>
              </ul>
            </div>
            <button class="d-block d-lg-none offcanvas-btn-close focus-reset" type="button" data-toggle="collapse" data-target="#mobile-menu" aria-controls="mobile-menu" aria-expanded="true" aria-label="Toggle navigation">
              <i class="gr-cross-icon"></i>
            </button>
          </div>
          <div class="header-btns header-btn-devider ml-auto pr-2 ml-lg-6 d-none d-xs-flex">
            {% if user.is_authenticated %}
              <a class="btn btn-transparent text-uppercase font-size-3 heading-default-color focus-reset" href="{% url 'accounts:logout' %}">خروج</a>
              {% if user.role == 'freelancer' %}
                <a class="btn btn-primary text-uppercase font-size-3" href="{% url 'accounts:freelancer_dashboard' %}">پروفایل </a>
              {% elif user.role == 'employer' %}
                <a class="btn btn-primary text-uppercase font-size-3" href="{% url 'accounts:employer_dashboard' %}">دشبورد کارفرما</a>
              {% endif %}
            {% else %}
              <a class="btn btn-transparent text-uppercase font-size-3 heading-default-color focus-reset" href="{% url 'accounts:login' %}">ورود</a>
              <a class="btn btn-primary text-uppercase font-size-3" href="{% url 'accounts:signup' %}">ثبت‌نام</a>
            {% endif %}
          </div>
          <!-- Mobile Menu Hamburger -->
          <button class="navbar-toggler btn-close-off-canvas hamburger-icon border-0" type="button" data-toggle="collapse" data-target="#mobile-menu" aria-controls="mobile-menu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="hamburger hamburger--squeeze js-hamburger">
              <span class="hamburger-box">
                <span class="hamburger-inner"></span>
              </span>
            </span>
          </button>
        </nav>
      </div>
    </header>
    <!-- Header End -->

    <!-- Content -->
    {% block content %}
    {% endblock %}

    <!-- Footer Area -->
    <footer class="footer bg-ebony-clay dark-mode-texts">
      <div class="container">
        <div class="pt-11 pt-lg-20 pb-13 pb-lg-20 border-bottom border-width-1 border-default-color-2">
          <div class="row justify-content-center">
            <div class="col-xl-7 col-lg-12" data-aos="fade-right" data-aos-duration="800" data-aos-once="true">
              <div class="pb-xl-0 pb-9 text-xl-right text-center">
                <h2 class="text-white font-size-8 mb-4">جامع‌ترین پورتال شغلی</h2>
                <p class="text-hit-gray font-size-5 mb-0">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از و از طراحان گرافیک است.</p>
              </div>
            </div>
            <div class="col-xl-5 col-lg-12" data-aos="fade-left" data-aos-duration="800" data-aos-once="true"></div>
          </div>
        </div>
        <div class="container pt-12 pt-lg-19 pb-10 pb-lg-19">
          <div class="row">
            <div class="col-lg-4 col-sm-6 mb-lg-0 mb-9">
              <img src="{% static 'image/logo-main-white.png' %}" alt="لوگوی جاب کمپ" class="footer-logo mb-14">
              <div class="media mb-11">
                <img src="{% static 'image/l1/png/message.png' %}" class="align-self-center mr-3" alt="">
                <div class="media-body pl-5">
                  <p class="mb-0 font-size-4 text-white">ارتباط با ما</p>
                  <a class="mb-0 font-size-4 font-weight-bold" href="mailto:support@uxtheme.net">support@uxtheme.net</a>
                </div>
              </div>
              <div class="social-icons">
                <ul class="pl-0 list-unstyled d-flex align-items-end">
                  <li class="d-flex flex-column justify-content-center px-3 mr-3 font-size-4 heading-default-color">ما را دنبال کنید در:</li>
                  <li class="d-flex flex-column justify-content-center px-3 mr-3"><a href="#" class="hover-color-primary heading-default-color"><i class="fab fa-facebook-f font-size-3 pt-2"></i></a></li>
                  <li class="d-flex flex-column justify-content-center px-3 mr-3"><a href="#" class="hover-color-primary heading-default-color"><i class="fab fa-twitter font-size-3 pt-2"></i></a></li>
                  <li class="d-flex flex-column justify-content-center px-3 mr-3"><a href="#" class="hover-color-primary heading-default-color"><i class="fab fa-linkedin-in font-size-3 pt-2"></i></a></li>
                </ul>
              </div>
            </div>
            <div class="col-lg-8 col-md-6">
              <div class="row">
                <div class="col-lg-3 col-md-6 col-sm-3 col-xs-6">
                  <div class="footer-widget widget2 mb-md-0 mb-13">
                    <p class="widget-title font-size-4 text-gray mb-md-8 mb-7">شرکت</p>
                    <ul class="widget-links pl-0 list-unstyled list-hover-primary">
                      <li class="mb-6"><a class="heading-default-color font-size-4 font-weight-normal" href="{% url 'website:home' %}#about">درباره ما</a></li>
                      <li class="mb-6"><a class="heading-default-color font-size-4 font-weight-normal" href="{% url 'website:contact' %}">تماس با ما</a></li>
                    </ul>
                  </div>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-3 col-xs-6">
                  <div class="footer-widget widget3 mb-sm-0 mb-13">
                    <p class="widget-title font-size-4 text-gray mb-md-8 mb-7">خدمات</p>
                    <ul class="widget-links pl-0 list-unstyled list-hover-primary">
                      <li class="mb-6"><a class="heading-default-color font-size-4 font-weight-normal" href="{% url 'website:home' %}#services">جستجوی شغل</a></li>
                      <li class="mb-6"><a class="heading-default-color font-size-4 font-weight-normal" href="{% url 'website:home' %}#services">پست شغل</a></li>
                    </ul>
                  </div>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-3 col-xs-6">
                  <div class="footer-widget widget4">
                    <p class="widget-title font-size-4 text-gray mb-md-8 mb-7">حقوقی</p>
                    <ul class="widget-links pl-0 list-unstyled list-hover-primary">
                      <li class="mb-6"><a class="heading-default-color font-size-4 font-weight-normal" href="{% url 'website:home' %}#privacy">سیاست حفظ حریم خصوصی</a></li>
                      <li class="mb-6"><a class="heading-default-color font-size-4 font-weight-normal" href="{% url 'website:home' %}#terms">قوانین و مقررات</a></li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>
    <!-- Footer End -->
  </div>
  <!-- Vendor Scripts -->
  <script src="{% static 'js/vendor.min.js' %}"></script>
  <script src="{% static 'js/custom.js' %}"></script>
</body>
</html>